# Generated by Django 4.2.6 on 2024-03-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('event_type', models.TextField()),
                ('description', models.TextField()),
                ('date_of_creation', models.DateTimeField()),
                ('event_duration', models.IntegerField()),
                ('tags', models.JSONField()),
                ('contact_info', models.JSONField()),
            ],
        ),
    ]
