# Generated by Django 4.2.6 on 2024-03-28 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0005_likedevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedevent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primary.event'),
        ),
        migrations.AlterField(
            model_name='likedevent',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primary.profile'),
        ),
    ]
