# Generated by Django 4.2.6 on 2024-03-29 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0006_alter_likedevent_event_alter_likedevent_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primary.profile'),
        ),
    ]
