# Generated by Django 4.2.6 on 2024-03-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0008_profiledetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='required_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
