# Generated by Django 4.2.6 on 2024-04-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0010_registeredevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_of_creation',
            new_name='event_date',
        ),
    ]
