# Generated by Django 4.2.6 on 2024-04-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0011_rename_date_of_creation_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='expiry_timer',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
