# Generated by Django 4.2.6 on 2024-04-26 16:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0012_event_expiry_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0.0), django.core.validators.MaxValueValidator(limit_value=100.0)])),
                ('review', models.TextField(blank=True, null=True)),
                ('event_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='primary.registeredevent')),
            ],
        ),
    ]
