# Generated by Django 5.0.4 on 2024-05-01 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0013_completedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bgimg',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='completedevent',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0.1), django.core.validators.MaxValueValidator(limit_value=5.0)]),
        ),
    ]
