# Generated by Django 5.0.4 on 2024-05-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0014_event_bgimg_alter_completedevent_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bgimg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
