# Generated by Django 5.0.4 on 2024-05-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0015_alter_event_bgimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bgimg',
            field=models.ImageField(blank=True, null=True, upload_to='images/events/'),
        ),
    ]
