# Generated by Django 5.0.4 on 2024-05-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0016_alter_event_bgimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetail',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
