# Generated by Django 5.0.4 on 2024-05-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0017_profiledetail_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetail',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/'),
        ),
    ]
